## Baseline

In [ ]:
import pandas as pd

In [ ]:
def read_file_as_df(file_name):
    import pandas as pd
    import csv

    import sys
    import pandas as pd

    maxInt = sys.maxsize

    while True:
        # decrease the maxInt value by factor 10
        # as long as the OverflowError occurs.

        try:
            csv.field_size_limit(maxInt)
            break
        except OverflowError:
            maxInt = int(maxInt/10)

    file = []
    col = []

    with open(file_name, encoding='latin-1') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=';')
        line_count = 0
        for row in csv_reader:
            if line_count==0:
                for r in row:
                    col.append(r)
                line_count+=1
            else:
                line = []
                for r in row:
                    line.append(r)
                file.append(line)
                line_count += 1


    df = pd.DataFrame(file, columns = col)
    return df

In [ ]:
df = read_file_as_df('../data/e-SIC1BR.csv')

In [ ]:
df.head(1)

,age-bracket,gender,education,profession,req-text,resp-text,resp-type,clarity,service,1funct-request,...,55work-response,56achieve-response,57leisure-response,58home-response,59money-response,60relig-response,61death-response,62assent-response,63nonfl-response,64filler-response
0,a31-42,m,e2,academy,"Prezados, Gostaria de solicitar informações so...","Não dispomos de vaga em aberto, para o cargo d...",Acesso Concedido,5,5,"0,4531",...,"0,0612","0,102","0,0204",0,0,0,0,0,0,0

In [ ]:
df['age-bracket'].value_counts()

a31-42    16978
a17-30    16769
a43-xx    14015
Name: age-bracket, dtype: int64

In [ ]:
df[df['age-bracket'].isna()]

Empty DataFrame
Columns: [age-bracket, gender, education, profession, req-text, resp-text, resp-type, clarity, service, 1funct-request, 2pronoun-request, 3ppron-request, 4i-request, 5we-request, 6you-request, 7shehe-request, 8they-request, 9ipron-request, 10article-request, 11verb-request, 12auxverb-request, 13past-request, 14present-request, 15future-request, 16adverb-request, 17preps-request, 18conj-request, 19negate-request, 20quant-request, 21number-request, 22swear-request, 23social-request, 24family-request, 25friend-request, 26humans-request, 27affect-request, 28posemo-request, 29negemo-request, 30anx-request, 31anger-request, 32sad-request, 33cogmech-request, 34insight-request, 35cause-request, 36discrep-request, 37tentat-request, 38certain-request, 39inhib-request, 40incl-request, 41excl-request, 42percept-request, 43see-request, 44hear-request, 45feel-request, 46bio-request, 47body-request, 48health-request, 49sexual-request, 50ingest-request, 51relativ-request, 52motion-request, 53space-request, 54time-request, 55work-request, 56achieve-request, 57leisure-request, 58home-request, 59money-request, 60relig-request, 61death-request, 62assent-request, 63nonfl-request, 64filler-request, 1funct-response, 2pronoun-response, 3ppron-response, 4i-response, 5we-response, 6you-response, 7shehe-response, 8they-response, 9ipron-response, 10article-response, 11verb-response, 12auxverb-response, 13past-response, 14present-response, 15future-response, 16adverb-response, 17preps-response, 18conj-response, 19negate-response, 20quant-response, 21number-response, 22swear-response, 23social-response, 24family-response, 25friend-response, 26humans-response, 27affect-response, ...]
Index: []

[0 rows x 137 columns]

In [ ]:
df[df['age-bracket']==""]

Empty DataFrame
Columns: [age-bracket, gender, education, profession, req-text, resp-text, resp-type, clarity, service, 1funct-request, 2pronoun-request, 3ppron-request, 4i-request, 5we-request, 6you-request, 7shehe-request, 8they-request, 9ipron-request, 10article-request, 11verb-request, 12auxverb-request, 13past-request, 14present-request, 15future-request, 16adverb-request, 17preps-request, 18conj-request, 19negate-request, 20quant-request, 21number-request, 22swear-request, 23social-request, 24family-request, 25friend-request, 26humans-request, 27affect-request, 28posemo-request, 29negemo-request, 30anx-request, 31anger-request, 32sad-request, 33cogmech-request, 34insight-request, 35cause-request, 36discrep-request, 37tentat-request, 38certain-request, 39inhib-request, 40incl-request, 41excl-request, 42percept-request, 43see-request, 44hear-request, 45feel-request, 46bio-request, 47body-request, 48health-request, 49sexual-request, 50ingest-request, 51relativ-request, 52motion-request, 53space-request, 54time-request, 55work-request, 56achieve-request, 57leisure-request, 58home-request, 59money-request, 60relig-request, 61death-request, 62assent-request, 63nonfl-request, 64filler-request, 1funct-response, 2pronoun-response, 3ppron-response, 4i-response, 5we-response, 6you-response, 7shehe-response, 8they-response, 9ipron-response, 10article-response, 11verb-response, 12auxverb-response, 13past-response, 14present-response, 15future-response, 16adverb-response, 17preps-response, 18conj-response, 19negate-response, 20quant-response, 21number-response, 22swear-response, 23social-response, 24family-response, 25friend-response, 26humans-response, 27affect-response, ...]
Index: []

[0 rows x 137 columns]

In [ ]:
X = df['req-text']
y = pd.factorize(df['age-bracket'])[0]

In [ ]:
X.shape, len(X.unique())

((47762,), 41454)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=115, stratify=y)

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

vocab_size = len(tokenizer.word_index) + 1  # Add 1 for padding

2024-11-02 16:06:33.208412: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-11-02 16:06:33.208430: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

AttributeError: 'float' object has no attribute 'lower'

In [ ]:
vocab_size

66644

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = tokenizer.texts_to_sequences(X_train)
X_train = pad_sequences(sequences, maxlen=200)

test_sequences = tokenizer.texts_to_sequences(X_test)
X_test = pad_sequences(test_sequences, maxlen=200)

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=115, stratify=y_train)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Embedding
from tensorflow.keras.callbacks import EarlyStopping

input_length = 200  # sequence length
embedding_size = 128  # embedding dimension

lstm_units = 4  # number of LSTM cells

dropout_rate = 0.5  # dropout rate

epochs = 20  # number of epochs
batch_size = 128  # batch size

learning_rate = 0.01  # learning rate

validation_split = 0.25  # validation set ratio

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length=input_length))
model.add(LSTM(lstm_units, return_sequences=False))
model.add(Dropout(dropout_rate))
model.add(Dense(3, activation='softmax'))

optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate) # qual optimizer usar?
model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

early_stopping = EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 200, 128)          8480256

 lstm (LSTM)                 (None, 4)                 2128

 dropout (Dropout)           (None, 4)                 0

2024-10-23 23:44:59.643808: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-10-23 23:44:59.644398: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-10-23 23:44:59.644446: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2024-10-23 23:44:59.644491: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2024-10-23 23:44:59.644534: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2024-10-23 23:44:59.644578: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2024-10-23 23:44:59.644623: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2024-10-23 23:44:59.644665: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2024-10-23 23:44:59.644708: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2024-10-23 23:44:59.644715: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-10-23 23:44:59.644920: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

 dense (Dense)               (None, 3)                 15

=================================================================
Total params: 8,482,399
Trainable params: 8,482,399
Non-trainable params: 0
_________________________________________________________________

In [ ]:
import numpy as np

y_train = np.array(y_train)
y_test = np.array(y_test)

In [ ]:
history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=128,
    validation_data=(X_val, y_val),
    callbacks=[early_stopping]
)

Epoch 1/20
224/224 [==============================] - 21s 87ms/step - loss: 1.0186 - accuracy: 0.4670 - val_loss: 0.9448 - val_accuracy: 0.5346
Epoch 2/20
224/224 [==============================] - 18s 82ms/step - loss: 0.8580 - accuracy: 0.5990 - val_loss: 0.9170 - val_accuracy: 0.5584
Epoch 3/20
224/224 [==============================] - 18s 82ms/step - loss: 0.7144 - accuracy: 0.6857 - val_loss: 0.9508 - val_accuracy: 0.5638
Epoch 4/20
224/224 [==============================] - 18s 82ms/step - loss: 0.6172 - accuracy: 0.7323 - val_loss: 0.9949 - val_accuracy: 0.5552
Epoch 5/20
224/224 [==============================] - 18s 82ms/step - loss: 0.5500 - accuracy: 0.7671 - val_loss: 1.0957 - val_accuracy: 0.5670
Epoch 6/20
224/224 [==============================] - 18s 82ms/step - loss: 0.4996 - accuracy: 0.7899 - val_loss: 1.1537 - val_accuracy: 0.5651
Epoch 7/20
224/224 [==============================] - 18s 81ms/step - loss: 0.4675 - accuracy: 0.8044 - val_loss: 1.2700 - val_accuracy: 0.5712
Epoch 8/20
224/224 [==============================] - 18s 82ms/step - loss: 0.4322 - accuracy: 0.8228 - val_loss: 1.3406 - val_accuracy: 0.5651
Epoch 9/20
224/224 [==============================] - 18s 82ms/step - loss: 0.4092 - accuracy: 0.8327 - val_loss: 1.4514 - val_accuracy: 0.5699
Epoch 10/20
224/224 [==============================] - 18s 82ms/step - loss: 0.3804 - accuracy: 0.8438 - val_loss: 1.5045 - val_accuracy: 0.5647
Epoch 11/20
224/224 [==============================] - 19s 83ms/step - loss: 0.3768 - accuracy: 0.8442 - val_loss: 1.5599 - val_accuracy: 0.5634
Epoch 12/20
224/224 [==============================] - 19s 84ms/step - loss: 0.3742 - accuracy: 0.8426 - val_loss: 1.5857 - val_accuracy: 0.5685

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Validation Accuracy: {accuracy}')

299/299 [==============================] - 2s 7ms/step - loss: 1.2758 - accuracy: 0.5669
Validation Accuracy: 0.5669423341751099

In [ ]:
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

from sklearn.metrics import f1_score
f1_score(y_test, y_pred_classes, average='weighted')

299/299 [==============================] - 2s 7ms/step

0.5672392776287271

In [ ]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
import tensorflow as tf

def create_model(input_length = 200, embedding_size=128, lstm_units=4, dropout_rate=0.5, learning_rate=0.01):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length=input_length))
    model.add(tf.keras.layers.LSTM(lstm_units, return_sequences=False))
    model.add(tf.keras.layers.Dropout(dropout_rate))
    model.add(tf.keras.layers.Dense(3, activation='softmax'))

    optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
    model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

    return model

In [ ]:
model_ = KerasClassifier(build_fn=create_model, epochs=20, batch_size=128)

param_grid = {
    'embedding_size': [128, 256],
    'lstm_units': [4, 16],
    'dropout_rate': [0.3, 0.5],
    'learning_rate': [0.001, 0.01],
}

grid = GridSearchCV(estimator=model_, param_grid=param_grid, cv=5, verbose=0)

grid_result = grid.fit(X_train, y_train, validation_data=(X_val, y_val), callbacks=[early_stopping])

In [ ]:
grid_result.best_params_, grid_result.best_score_

({'dropout_rate': 0.5,
  'embedding_size': 256,
  'learning_rate': 0.001,
  'lstm_units': 16},
 0.5749231100082397)

In [ ]:
f1 = []
for i in range(10):

    gs_model = create_model(input_length = 200, embedding_size=256, lstm_units=16, dropout_rate=0.5, learning_rate=0.001)

    history = gs_model.fit(
        X_train, y_train,
        epochs=20,
        batch_size=128,
        validation_data=(X_val, y_val),
        callbacks=[early_stopping]
    )

    y_pred = model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)

    f1.append(f1_score(y_test, y_pred_classes, average='weighted'))

print(f1)

Epoch 1/20
224/224 [==============================] - 81s 348ms/step - loss: 0.9965 - accuracy: 0.4863 - val_loss: 0.8879 - val_accuracy: 0.5688
Epoch 2/20
224/224 [==============================] - 79s 353ms/step - loss: 0.7447 - accuracy: 0.6831 - val_loss: 0.8692 - val_accuracy: 0.5879
Epoch 3/20
224/224 [==============================] - 78s 350ms/step - loss: 0.5110 - accuracy: 0.8100 - val_loss: 0.9718 - val_accuracy: 0.5880
Epoch 4/20
224/224 [==============================] - 77s 343ms/step - loss: 0.3419 - accuracy: 0.8829 - val_loss: 1.1629 - val_accuracy: 0.5865
Epoch 5/20
224/224 [==============================] - 71s 317ms/step - loss: 0.2436 - accuracy: 0.9213 - val_loss: 1.3496 - val_accuracy: 0.5764
Epoch 6/20
224/224 [==============================] - 35s 158ms/step - loss: 0.1827 - accuracy: 0.9425 - val_loss: 1.5187 - val_accuracy: 0.5801
Epoch 7/20
224/224 [==============================] - 35s 158ms/step - loss: 0.1512 - accuracy: 0.9529 - val_loss: 1.6925 - val_accuracy: 0.5752
Epoch 8/20
224/224 [==============================] - 35s 157ms/step - loss: 0.1338 - accuracy: 0.9559 - val_loss: 1.7615 - val_accuracy: 0.5745
299/299 [==============================] - 2s 6ms/step
Epoch 1/20
224/224 [==============================] - 36s 156ms/step - loss: 0.9919 - accuracy: 0.4941 - val_loss: 0.8895 - val_accuracy: 0.5741
Epoch 2/20
224/224 [==============================] - 35s 158ms/step - loss: 0.7473 - accuracy: 0.6857 - val_loss: 0.8698 - val_accuracy: 0.5904
Epoch 3/20
224/224 [==============================] - 35s 157ms/step - loss: 0.5231 - accuracy: 0.8044 - val_loss: 0.9572 - val_accuracy: 0.5896
Epoch 4/20
224/224 [==============================] - 36s 161ms/step - loss: 0.3692 - accuracy: 0.8698 - val_loss: 1.1366 - val_accuracy: 0.5755
Epoch 5/20
224/224 [==============================] - 47s 208ms/step - loss: 0.2822 - accuracy: 0.9051 - val_loss: 1.2871 - val_accuracy: 0.5788
Epoch 6/20
224/224 [==============================] - 47s 209ms/step - loss: 0.2169 - accuracy: 0.9285 - val_loss: 1.5178 - val_accuracy: 0.5782
Epoch 7/20
224/224 [==============================] - 49s 218ms/step - loss: 0.1748 - accuracy: 0.9429 - val_loss: 1.6189 - val_accuracy: 0.5812
299/299 [==============================] - 3s 9ms/step
Epoch 1/20
224/224 [==============================] - 50s 215ms/step - loss: 0.9827 - accuracy: 0.4992 - val_loss: 0.8821 - val_accuracy: 0.5746
Epoch 2/20
224/224 [==============================] - 53s 239ms/step - loss: 0.7390 - accuracy: 0.6896 - val_loss: 0.8738 - val_accuracy: 0.5874
Epoch 3/20
224/224 [==============================] - 54s 242ms/step - loss: 0.5226 - accuracy: 0.8041 - val_loss: 0.9864 - val_accuracy: 0.5847
Epoch 4/20
224/224 [==============================] - 52s 230ms/step - loss: 0.3726 - accuracy: 0.8692 - val_loss: 1.1311 - val_accuracy: 0.5807
Epoch 5/20
224/224 [==============================] - 54s 240ms/step - loss: 0.2650 - accuracy: 0.9114 - val_loss: 1.3173 - val_accuracy: 0.5854
Epoch 6/20
224/224 [==============================] - 60s 266ms/step - loss: 0.2071 - accuracy: 0.9338 - val_loss: 1.4681 - val_accuracy: 0.5820
Epoch 7/20
224/224 [==============================] - 97s 433ms/step - loss: 0.1860 - accuracy: 0.9394 - val_loss: 1.5470 - val_accuracy: 0.5843
299/299 [==============================] - 6s 21ms/step
Epoch 1/20
224/224 [==============================] - 91s 389ms/step - loss: 0.9791 - accuracy: 0.5015 - val_loss: 0.8744 - val_accuracy: 0.5826
Epoch 2/20
224/224 [==============================] - 87s 388ms/step - loss: 0.7281 - accuracy: 0.6923 - val_loss: 0.8700 - val_accuracy: 0.5890
Epoch 3/20
224/224 [==============================] - 107s 475ms/step - loss: 0.5003 - accuracy: 0.8140 - val_loss: 0.9629 - val_accuracy: 0.5810
Epoch 4/20
224/224 [==============================] - 114s 509ms/step - loss: 0.3462 - accuracy: 0.8770 - val_loss: 1.1092 - val_accuracy: 0.5862
Epoch 5/20
224/224 [==============================] - 106s 472ms/step - loss: 0.2590 - accuracy: 0.9131 - val_loss: 1.2668 - val_accuracy: 0.5790
Epoch 6/20
224/224 [==============================] - 100s 445ms/step - loss: 0.2103 - accuracy: 0.9309 - val_loss: 1.4592 - val_accuracy: 0.5797
Epoch 7/20
224/224 [==============================] - 104s 463ms/step - loss: 0.1764 - accuracy: 0.9420 - val_loss: 1.6110 - val_accuracy: 0.5747
299/299 [==============================] - 8s 28ms/step
Epoch 1/20
224/224 [==============================] - 110s 468ms/step - loss: 0.9896 - accuracy: 0.4935 - val_loss: 0.8770 - val_accuracy: 0.5817
Epoch 2/20
224/224 [==============================] - 109s 485ms/step - loss: 0.7388 - accuracy: 0.6875 - val_loss: 0.8722 - val_accuracy: 0.5886
Epoch 3/20
224/224 [==============================] - 106s 475ms/step - loss: 0.5112 - accuracy: 0.8083 - val_loss: 0.9811 - val_accuracy: 0.5928
Epoch 4/20
224/224 [==============================] - 87s 391ms/step - loss: 0.3603 - accuracy: 0.8733 - val_loss: 1.1339 - val_accuracy: 0.5870
Epoch 5/20
224/224 [==============================] - 110s 493ms/step - loss: 0.2616 - accuracy: 0.9111 - val_loss: 1.3041 - val_accuracy: 0.5887
Epoch 6/20
224/224 [==============================] - 108s 482ms/step - loss: 0.2060 - accuracy: 0.9325 - val_loss: 1.4261 - val_accuracy: 0.5702
Epoch 7/20
224/224 [==============================] - 71s 317ms/step - loss: 0.1703 - accuracy: 0.9463 - val_loss: 1.6717 - val_accuracy: 0.5777
Epoch 8/20
224/224 [==============================] - 110s 488ms/step - loss: 0.1286 - accuracy: 0.9597 - val_loss: 1.7583 - val_accuracy: 0.5734
299/299 [==============================] - 7s 25ms/step
Epoch 1/20
224/224 [==============================] - 68s 290ms/step - loss: 0.9918 - accuracy: 0.4829 - val_loss: 0.8893 - val_accuracy: 0.5615
Epoch 2/20
224/224 [==============================] - 67s 298ms/step - loss: 0.7571 - accuracy: 0.6770 - val_loss: 0.8835 - val_accuracy: 0.5787
Epoch 3/20
224/224 [==============================] - 61s 270ms/step - loss: 0.5295 - accuracy: 0.7974 - val_loss: 1.0048 - val_accuracy: 0.5840
Epoch 4/20
224/224 [==============================] - 70s 314ms/step - loss: 0.3706 - accuracy: 0.8654 - val_loss: 1.1582 - val_accuracy: 0.5766
Epoch 5/20
224/224 [==============================] - 62s 278ms/step - loss: 0.2728 - accuracy: 0.9054 - val_loss: 1.2604 - val_accuracy: 0.5705
Epoch 6/20
224/224 [==============================] - 68s 302ms/step - loss: 0.2174 - accuracy: 0.9275 - val_loss: 1.4495 - val_accuracy: 0.5754
Epoch 7/20
224/224 [==============================] - 61s 272ms/step - loss: 0.1635 - accuracy: 0.9463 - val_loss: 1.6946 - val_accuracy: 0.5754
Epoch 8/20
224/224 [==============================] - 70s 311ms/step - loss: 0.1346 - accuracy: 0.9555 - val_loss: 1.7988 - val_accuracy: 0.5770
299/299 [==============================] - 3s 8ms/step
Epoch 1/20
224/224 [==============================] - 72s 307ms/step - loss: 0.9960 - accuracy: 0.4845 - val_loss: 0.8930 - val_accuracy: 0.5638
Epoch 2/20
224/224 [==============================] - 68s 306ms/step - loss: 0.7469 - accuracy: 0.6808 - val_loss: 0.8748 - val_accuracy: 0.5891
Epoch 3/20
224/224 [==============================] - 68s 306ms/step - loss: 0.5174 - accuracy: 0.8043 - val_loss: 1.0067 - val_accuracy: 0.5773
Epoch 4/20
224/224 [==============================] - 65s 289ms/step - loss: 0.3663 - accuracy: 0.8684 - val_loss: 1.1490 - val_accuracy: 0.5821
Epoch 5/20
224/224 [==============================] - 66s 296ms/step - loss: 0.2766 - accuracy: 0.9040 - val_loss: 1.2916 - val_accuracy: 0.5726
Epoch 6/20
224/224 [==============================] - 68s 302ms/step - loss: 0.2133 - accuracy: 0.9296 - val_loss: 1.4837 - val_accuracy: 0.5770
Epoch 7/20
224/224 [==============================] - 67s 297ms/step - loss: 0.1733 - accuracy: 0.9445 - val_loss: 1.7297 - val_accuracy: 0.5830
299/299 [==============================] - 4s 14ms/step
Epoch 1/20
224/224 [==============================] - 72s 310ms/step - loss: 0.9925 - accuracy: 0.4947 - val_loss: 0.8783 - val_accuracy: 0.5814
Epoch 2/20
224/224 [==============================] - 68s 303ms/step - loss: 0.7424 - accuracy: 0.6878 - val_loss: 0.8654 - val_accuracy: 0.5868
Epoch 3/20
224/224 [==============================] - 65s 291ms/step - loss: 0.5150 - accuracy: 0.8079 - val_loss: 0.9756 - val_accuracy: 0.5862
Epoch 4/20
224/224 [==============================] - 70s 313ms/step - loss: 0.3613 - accuracy: 0.8717 - val_loss: 1.1174 - val_accuracy: 0.5869
Epoch 5/20
224/224 [==============================] - 69s 307ms/step - loss: 0.2682 - accuracy: 0.9110 - val_loss: 1.4308 - val_accuracy: 0.5857
Epoch 6/20
224/224 [==============================] - 67s 300ms/step - loss: 0.2303 - accuracy: 0.9220 - val_loss: 1.4328 - val_accuracy: 0.5841
Epoch 7/20
224/224 [==============================] - 66s 293ms/step - loss: 0.1668 - accuracy: 0.9471 - val_loss: 1.5786 - val_accuracy: 0.5877
Epoch 8/20
224/224 [==============================] - 67s 299ms/step - loss: 0.1367 - accuracy: 0.9571 - val_loss: 1.6528 - val_accuracy: 0.5854
Epoch 9/20
224/224 [==============================] - 62s 276ms/step - loss: 0.1164 - accuracy: 0.9636 - val_loss: 1.9906 - val_accuracy: 0.5859
Epoch 10/20
224/224 [==============================] - 66s 296ms/step - loss: 0.1140 - accuracy: 0.9653 - val_loss: 1.9612 - val_accuracy: 0.5816
Epoch 11/20
224/224 [==============================] - 67s 301ms/step - loss: 0.0877 - accuracy: 0.9737 - val_loss: 2.0891 - val_accuracy: 0.5797
Epoch 12/20
224/224 [==============================] - 64s 286ms/step - loss: 0.0695 - accuracy: 0.9782 - val_loss: 2.4034 - val_accuracy: 0.5787
299/299 [==============================] - 5s 17ms/step
Epoch 1/20
224/224 [==============================] - 70s 302ms/step - loss: 0.9947 - accuracy: 0.4896 - val_loss: 0.8948 - val_accuracy: 0.5657
Epoch 2/20
224/224 [==============================] - 63s 283ms/step - loss: 0.7429 - accuracy: 0.6870 - val_loss: 0.8824 - val_accuracy: 0.5851
Epoch 3/20
224/224 [==============================] - 64s 285ms/step - loss: 0.5094 - accuracy: 0.8107 - val_loss: 0.9831 - val_accuracy: 0.5893
Epoch 4/20
224/224 [==============================] - 66s 296ms/step - loss: 0.3455 - accuracy: 0.8806 - val_loss: 1.1588 - val_accuracy: 0.5837
Epoch 5/20
224/224 [==============================] - 67s 300ms/step - loss: 0.2535 - accuracy: 0.9161 - val_loss: 1.3180 - val_accuracy: 0.5746
Epoch 6/20
224/224 [==============================] - 64s 286ms/step - loss: 0.1892 - accuracy: 0.9399 - val_loss: 1.5166 - val_accuracy: 0.5826
Epoch 7/20
224/224 [==============================] - 68s 302ms/step - loss: 0.1634 - accuracy: 0.9479 - val_loss: 1.6387 - val_accuracy: 0.5774
Epoch 8/20
224/224 [==============================] - 64s 287ms/step - loss: 0.1246 - accuracy: 0.9614 - val_loss: 1.8630 - val_accuracy: 0.5728
299/299 [==============================] - 4s 14ms/step
Epoch 1/20
224/224 [==============================] - 72s 310ms/step - loss: 0.9916 - accuracy: 0.4944 - val_loss: 0.8792 - val_accuracy: 0.5804
Epoch 2/20
224/224 [==============================] - 70s 311ms/step - loss: 0.7466 - accuracy: 0.6830 - val_loss: 0.8654 - val_accuracy: 0.5920
Epoch 3/20
224/224 [==============================] - 66s 293ms/step - loss: 0.5229 - accuracy: 0.8038 - val_loss: 0.9582 - val_accuracy: 0.5948
Epoch 4/20
224/224 [==============================] - 70s 314ms/step - loss: 0.3695 - accuracy: 0.8712 - val_loss: 1.0755 - val_accuracy: 0.5883
Epoch 5/20
224/224 [==============================] - 65s 292ms/step - loss: 0.2820 - accuracy: 0.9068 - val_loss: 1.3051 - val_accuracy: 0.5934
Epoch 6/20
224/224 [==============================] - 84s 374ms/step - loss: 0.2229 - accuracy: 0.9271 - val_loss: 1.4337 - val_accuracy: 0.5909
Epoch 7/20
224/224 [==============================] - 119s 532ms/step - loss: 0.1714 - accuracy: 0.9456 - val_loss: 1.4968 - val_accuracy: 0.5859
Epoch 8/20
224/224 [==============================] - 113s 505ms/step - loss: 0.1309 - accuracy: 0.9586 - val_loss: 1.7593 - val_accuracy: 0.5875
299/299 [==============================] - 9s 29ms/step
[0.5635375700739018, 0.5635375700739018, 0.5635375700739018, 0.5635375700739018, 0.5635375700739018, 0.5635375700739018, 0.5635375700739018, 0.5635375700739018, 0.5635375700739018, 0.5635375700739018]

In [ ]:
seeds = [11, 114, 115, 289, 42, 685, 383, 67]
f1=[]

X = df['req-text']
y = pd.factorize(df['age-bracket'])[0]

for seed in seeds:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed, stratify=y)
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(X_train)

    vocab_size = len(tokenizer.word_index) + 1

    sequences = tokenizer.texts_to_sequences(X_train)
    X_train = pad_sequences(sequences, maxlen=200)

    test_sequences = tokenizer.texts_to_sequences(X_test)
    X_test = pad_sequences(test_sequences, maxlen=200)

    X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=seed, stratify=y_train)

    y_train = np.array(y_train)
    y_test = np.array(y_test)

    model = create_model()

    history = model.fit(
        X_train, y_train,
        epochs=20,
        batch_size=128,
        validation_data=(X_val, y_val),
        callbacks=[early_stopping]
    )

    y_pred = model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)

    f1.append(f1_score(y_test, y_pred_classes, average='weighted'))

Epoch 1/20
224/224 [==============================] - 49s 206ms/step - loss: 1.0153 - accuracy: 0.4578 - val_loss: 0.9190 - val_accuracy: 0.5498
Epoch 2/20
224/224 [==============================] - 46s 207ms/step - loss: 0.8486 - accuracy: 0.5984 - val_loss: 0.9098 - val_accuracy: 0.5565
Epoch 3/20
224/224 [==============================] - 47s 210ms/step - loss: 0.7090 - accuracy: 0.6724 - val_loss: 0.9389 - val_accuracy: 0.5717
Epoch 4/20
224/224 [==============================] - 46s 206ms/step - loss: 0.6155 - accuracy: 0.7257 - val_loss: 1.0042 - val_accuracy: 0.5697
Epoch 5/20
224/224 [==============================] - 45s 203ms/step - loss: 0.5406 - accuracy: 0.7622 - val_loss: 1.0695 - val_accuracy: 0.5684
Epoch 6/20
224/224 [==============================] - 42s 188ms/step - loss: 0.4904 - accuracy: 0.7818 - val_loss: 1.1944 - val_accuracy: 0.5734
Epoch 7/20
224/224 [==============================] - 40s 179ms/step - loss: 0.4627 - accuracy: 0.7952 - val_loss: 1.2144 - val_accuracy: 0.5765
Epoch 8/20
224/224 [==============================] - 41s 183ms/step - loss: 0.4295 - accuracy: 0.8119 - val_loss: 1.2552 - val_accuracy: 0.5756
Epoch 9/20
224/224 [==============================] - 46s 204ms/step - loss: 0.4100 - accuracy: 0.8204 - val_loss: 1.3634 - val_accuracy: 0.5748
Epoch 10/20
224/224 [==============================] - 46s 206ms/step - loss: 0.3934 - accuracy: 0.8316 - val_loss: 1.3686 - val_accuracy: 0.5762
Epoch 11/20
224/224 [==============================] - 46s 205ms/step - loss: 0.3842 - accuracy: 0.8313 - val_loss: 1.5068 - val_accuracy: 0.5742
Epoch 12/20
224/224 [==============================] - 47s 209ms/step - loss: 0.3725 - accuracy: 0.8397 - val_loss: 1.5201 - val_accuracy: 0.5691
299/299 [==============================] - 6s 19ms/step
Epoch 1/20
224/224 [==============================] - 58s 244ms/step - loss: 1.0125 - accuracy: 0.4709 - val_loss: 0.9400 - val_accuracy: 0.5374
Epoch 2/20
224/224 [==============================] - 46s 206ms/step - loss: 0.8518 - accuracy: 0.6006 - val_loss: 0.9286 - val_accuracy: 0.5508
Epoch 3/20
224/224 [==============================] - 47s 210ms/step - loss: 0.7129 - accuracy: 0.6864 - val_loss: 0.9545 - val_accuracy: 0.5572
Epoch 4/20
224/224 [==============================] - 48s 214ms/step - loss: 0.6154 - accuracy: 0.7302 - val_loss: 1.0285 - val_accuracy: 0.5603
Epoch 5/20
224/224 [==============================] - 47s 209ms/step - loss: 0.5421 - accuracy: 0.7736 - val_loss: 1.1223 - val_accuracy: 0.5565
Epoch 6/20
224/224 [==============================] - 48s 213ms/step - loss: 0.4988 - accuracy: 0.7910 - val_loss: 1.2232 - val_accuracy: 0.5598
Epoch 7/20
224/224 [==============================] - 46s 204ms/step - loss: 0.4646 - accuracy: 0.8047 - val_loss: 1.3270 - val_accuracy: 0.5607
Epoch 8/20
224/224 [==============================] - 45s 200ms/step - loss: 0.4240 - accuracy: 0.8233 - val_loss: 1.4159 - val_accuracy: 0.5525
Epoch 9/20
224/224 [==============================] - 45s 200ms/step - loss: 0.4128 - accuracy: 0.8277 - val_loss: 1.4282 - val_accuracy: 0.5516
Epoch 10/20
224/224 [==============================] - 46s 205ms/step - loss: 0.3979 - accuracy: 0.8356 - val_loss: 1.5472 - val_accuracy: 0.5545
Epoch 11/20
224/224 [==============================] - 44s 198ms/step - loss: 0.3795 - accuracy: 0.8389 - val_loss: 1.6154 - val_accuracy: 0.5547
Epoch 12/20
224/224 [==============================] - 47s 212ms/step - loss: 0.3557 - accuracy: 0.8495 - val_loss: 1.7213 - val_accuracy: 0.5598
299/299 [==============================] - 9s 26ms/step
Epoch 1/20
224/224 [==============================] - 71s 302ms/step - loss: 1.0167 - accuracy: 0.4602 - val_loss: 0.9298 - val_accuracy: 0.5402
Epoch 2/20
224/224 [==============================] - 69s 307ms/step - loss: 0.8404 - accuracy: 0.6064 - val_loss: 0.9196 - val_accuracy: 0.5558
Epoch 3/20
224/224 [==============================] - 74s 332ms/step - loss: 0.6948 - accuracy: 0.6921 - val_loss: 0.9676 - val_accuracy: 0.5575
Epoch 4/20
224/224 [==============================] - 72s 323ms/step - loss: 0.6000 - accuracy: 0.7410 - val_loss: 1.0343 - val_accuracy: 0.5623
Epoch 5/20
224/224 [==============================] - 76s 341ms/step - loss: 0.5291 - accuracy: 0.7746 - val_loss: 1.1219 - val_accuracy: 0.5573
Epoch 6/20
224/224 [==============================] - 61s 274ms/step - loss: 0.4883 - accuracy: 0.7886 - val_loss: 1.1903 - val_accuracy: 0.5608
Epoch 7/20
224/224 [==============================] - 75s 335ms/step - loss: 0.4467 - accuracy: 0.8056 - val_loss: 1.2867 - val_accuracy: 0.5627
Epoch 8/20
224/224 [==============================] - 48s 214ms/step - loss: 0.4193 - accuracy: 0.8159 - val_loss: 1.3779 - val_accuracy: 0.5657
Epoch 9/20
224/224 [==============================] - 70s 314ms/step - loss: 0.3886 - accuracy: 0.8274 - val_loss: 1.4707 - val_accuracy: 0.5603
Epoch 10/20
224/224 [==============================] - 68s 306ms/step - loss: 0.3809 - accuracy: 0.8374 - val_loss: 1.5022 - val_accuracy: 0.5627
Epoch 11/20
224/224 [==============================] - 56s 251ms/step - loss: 0.3707 - accuracy: 0.8423 - val_loss: 1.6512 - val_accuracy: 0.5635
Epoch 12/20
224/224 [==============================] - 45s 199ms/step - loss: 0.3609 - accuracy: 0.8458 - val_loss: 1.6546 - val_accuracy: 0.5654
Epoch 13/20
224/224 [==============================] - 44s 198ms/step - loss: 0.3448 - accuracy: 0.8512 - val_loss: 1.7967 - val_accuracy: 0.5613
299/299 [==============================] - 6s 18ms/step
Epoch 1/20
224/224 [==============================] - 49s 207ms/step - loss: 1.0147 - accuracy: 0.4601 - val_loss: 0.9323 - val_accuracy: 0.5442
Epoch 2/20
224/224 [==============================] - 44s 198ms/step - loss: 0.8520 - accuracy: 0.6045 - val_loss: 0.9166 - val_accuracy: 0.5543
Epoch 3/20
224/224 [==============================] - 42s 186ms/step - loss: 0.7169 - accuracy: 0.6807 - val_loss: 0.9457 - val_accuracy: 0.5660
Epoch 4/20
224/224 [==============================] - 41s 185ms/step - loss: 0.6091 - accuracy: 0.7351 - val_loss: 1.0199 - val_accuracy: 0.5639
Epoch 5/20
224/224 [==============================] - 49s 218ms/step - loss: 0.5455 - accuracy: 0.7646 - val_loss: 1.1021 - val_accuracy: 0.5677
Epoch 6/20
224/224 [==============================] - 77s 345ms/step - loss: 0.4889 - accuracy: 0.7877 - val_loss: 1.1616 - val_accuracy: 0.5708
Epoch 7/20
224/224 [==============================] - 72s 324ms/step - loss: 0.4596 - accuracy: 0.7984 - val_loss: 1.2423 - val_accuracy: 0.5684
Epoch 8/20
224/224 [==============================] - 74s 332ms/step - loss: 0.4288 - accuracy: 0.8081 - val_loss: 1.4759 - val_accuracy: 0.5561
Epoch 9/20
224/224 [==============================] - 69s 309ms/step - loss: 0.4094 - accuracy: 0.8196 - val_loss: 1.4825 - val_accuracy: 0.5606
Epoch 10/20
224/224 [==============================] - 58s 260ms/step - loss: 0.3936 - accuracy: 0.8226 - val_loss: 1.5096 - val_accuracy: 0.5624
Epoch 11/20
224/224 [==============================] - 79s 352ms/step - loss: 0.3765 - accuracy: 0.8302 - val_loss: 1.5525 - val_accuracy: 0.5644
299/299 [==============================] - 10s 29ms/step
Epoch 1/20
224/224 [==============================] - 80s 342ms/step - loss: 1.0113 - accuracy: 0.4645 - val_loss: 0.9355 - val_accuracy: 0.5464
Epoch 2/20
224/224 [==============================] - 77s 342ms/step - loss: 0.8393 - accuracy: 0.6020 - val_loss: 0.9107 - val_accuracy: 0.5634
Epoch 3/20
224/224 [==============================] - 73s 324ms/step - loss: 0.6917 - accuracy: 0.6816 - val_loss: 0.9645 - val_accuracy: 0.5627
Epoch 4/20
224/224 [==============================] - 76s 338ms/step - loss: 0.6005 - accuracy: 0.7289 - val_loss: 1.0595 - val_accuracy: 0.5590
Epoch 5/20
224/224 [==============================] - 76s 338ms/step - loss: 0.5272 - accuracy: 0.7629 - val_loss: 1.0865 - val_accuracy: 0.5613
Epoch 6/20
224/224 [==============================] - 72s 320ms/step - loss: 0.4804 - accuracy: 0.7856 - val_loss: 1.1756 - val_accuracy: 0.5644
Epoch 7/20
224/224 [==============================] - 70s 315ms/step - loss: 0.4443 - accuracy: 0.8001 - val_loss: 1.3630 - val_accuracy: 0.5641
Epoch 8/20
224/224 [==============================] - 62s 278ms/step - loss: 0.4161 - accuracy: 0.8118 - val_loss: 1.4414 - val_accuracy: 0.5634
Epoch 9/20
224/224 [==============================] - 60s 269ms/step - loss: 0.3937 - accuracy: 0.8154 - val_loss: 1.5590 - val_accuracy: 0.5602
Epoch 10/20
224/224 [==============================] - 47s 211ms/step - loss: 0.3761 - accuracy: 0.8172 - val_loss: 1.5481 - val_accuracy: 0.5581
Epoch 11/20
224/224 [==============================] - 43s 190ms/step - loss: 0.3619 - accuracy: 0.8254 - val_loss: 1.6894 - val_accuracy: 0.5668
Epoch 12/20
224/224 [==============================] - 43s 192ms/step - loss: 0.3581 - accuracy: 0.8327 - val_loss: 1.7053 - val_accuracy: 0.5656
Epoch 13/20
224/224 [==============================] - 42s 190ms/step - loss: 0.3553 - accuracy: 0.8432 - val_loss: 1.7862 - val_accuracy: 0.5599
Epoch 14/20
224/224 [==============================] - 46s 204ms/step - loss: 0.3332 - accuracy: 0.8522 - val_loss: 1.7976 - val_accuracy: 0.5594
Epoch 15/20
224/224 [==============================] - 48s 215ms/step - loss: 0.3346 - accuracy: 0.8548 - val_loss: 1.8130 - val_accuracy: 0.5500
Epoch 16/20
224/224 [==============================] - 47s 209ms/step - loss: 0.3760 - accuracy: 0.8402 - val_loss: 1.7701 - val_accuracy: 0.5617
299/299 [==============================] - 6s 18ms/step
Epoch 1/20
224/224 [==============================] - 52s 221ms/step - loss: 1.0224 - accuracy: 0.4596 - val_loss: 0.9429 - val_accuracy: 0.5332
Epoch 2/20
224/224 [==============================] - 48s 212ms/step - loss: 0.8517 - accuracy: 0.6014 - val_loss: 0.9287 - val_accuracy: 0.5491
Epoch 3/20
224/224 [==============================] - 49s 219ms/step - loss: 0.7151 - accuracy: 0.6835 - val_loss: 0.9535 - val_accuracy: 0.5548
Epoch 4/20
224/224 [==============================] - 64s 284ms/step - loss: 0.6305 - accuracy: 0.7246 - val_loss: 0.9871 - val_accuracy: 0.5680
Epoch 5/20
224/224 [==============================] - 67s 299ms/step - loss: 0.5577 - accuracy: 0.7594 - val_loss: 1.0771 - val_accuracy: 0.5583
Epoch 6/20
224/224 [==============================] - 53s 238ms/step - loss: 0.5098 - accuracy: 0.7828 - val_loss: 1.1805 - val_accuracy: 0.5652
Epoch 7/20
224/224 [==============================] - 71s 317ms/step - loss: 0.4690 - accuracy: 0.8027 - val_loss: 1.3353 - val_accuracy: 0.5660
Epoch 8/20
224/224 [==============================] - 46s 206ms/step - loss: 0.4396 - accuracy: 0.8160 - val_loss: 1.3163 - val_accuracy: 0.5588
Epoch 9/20
224/224 [==============================] - 70s 312ms/step - loss: 0.4116 - accuracy: 0.8277 - val_loss: 1.3692 - val_accuracy: 0.5576
299/299 [==============================] - 9s 27ms/step
Epoch 1/20
224/224 [==============================] - 77s 330ms/step - loss: 1.0114 - accuracy: 0.4653 - val_loss: 0.9347 - val_accuracy: 0.5406
Epoch 2/20
224/224 [==============================] - 70s 314ms/step - loss: 0.8440 - accuracy: 0.6091 - val_loss: 0.9096 - val_accuracy: 0.5615
Epoch 3/20
224/224 [==============================] - 64s 285ms/step - loss: 0.6984 - accuracy: 0.6992 - val_loss: 0.9505 - val_accuracy: 0.5735
Epoch 4/20
224/224 [==============================] - 49s 218ms/step - loss: 0.6016 - accuracy: 0.7534 - val_loss: 1.0288 - val_accuracy: 0.5654
Epoch 5/20
224/224 [==============================] - 73s 327ms/step - loss: 0.5316 - accuracy: 0.7844 - val_loss: 1.1143 - val_accuracy: 0.5699
Epoch 6/20
224/224 [==============================] - 71s 320ms/step - loss: 0.4871 - accuracy: 0.8028 - val_loss: 1.2539 - val_accuracy: 0.5724
Epoch 7/20
224/224 [==============================] - 70s 312ms/step - loss: 0.4578 - accuracy: 0.8137 - val_loss: 1.3296 - val_accuracy: 0.5704
Epoch 8/20
224/224 [==============================] - 74s 330ms/step - loss: 0.4351 - accuracy: 0.8248 - val_loss: 1.3626 - val_accuracy: 0.5778
Epoch 9/20
224/224 [==============================] - 66s 296ms/step - loss: 0.4089 - accuracy: 0.8358 - val_loss: 1.3945 - val_accuracy: 0.5722
Epoch 10/20
224/224 [==============================] - 53s 235ms/step - loss: 0.3929 - accuracy: 0.8402 - val_loss: 1.4844 - val_accuracy: 0.5725
Epoch 11/20
224/224 [==============================] - 72s 321ms/step - loss: 0.3749 - accuracy: 0.8466 - val_loss: 1.6391 - val_accuracy: 0.5696
Epoch 12/20
224/224 [==============================] - 49s 218ms/step - loss: 0.3655 - accuracy: 0.8494 - val_loss: 1.7104 - val_accuracy: 0.5712
Epoch 13/20
224/224 [==============================] - 47s 211ms/step - loss: 0.3561 - accuracy: 0.8509 - val_loss: 1.6812 - val_accuracy: 0.5717
299/299 [==============================] - 7s 20ms/step
Epoch 1/20
224/224 [==============================] - 51s 214ms/step - loss: 1.0214 - accuracy: 0.4629 - val_loss: 0.9354 - val_accuracy: 0.5457
Epoch 2/20
224/224 [==============================] - 46s 207ms/step - loss: 0.8511 - accuracy: 0.6033 - val_loss: 0.9068 - val_accuracy: 0.5670
Epoch 3/20
224/224 [==============================] - 47s 208ms/step - loss: 0.7051 - accuracy: 0.6866 - val_loss: 0.9369 - val_accuracy: 0.5727
Epoch 4/20
224/224 [==============================] - 47s 211ms/step - loss: 0.6120 - accuracy: 0.7264 - val_loss: 1.0171 - val_accuracy: 0.5733
Epoch 5/20
224/224 [==============================] - 45s 203ms/step - loss: 0.5453 - accuracy: 0.7537 - val_loss: 1.0498 - val_accuracy: 0.5682
Epoch 6/20
224/224 [==============================] - 46s 207ms/step - loss: 0.4981 - accuracy: 0.7737 - val_loss: 1.1763 - val_accuracy: 0.5737
Epoch 7/20
224/224 [==============================] - 44s 195ms/step - loss: 0.4552 - accuracy: 0.7967 - val_loss: 1.2566 - val_accuracy: 0.5680
Epoch 8/20
224/224 [==============================] - 58s 260ms/step - loss: 0.4280 - accuracy: 0.8107 - val_loss: 1.2755 - val_accuracy: 0.5660
Epoch 9/20
224/224 [==============================] - 69s 310ms/step - loss: 0.4103 - accuracy: 0.8230 - val_loss: 1.4113 - val_accuracy: 0.5762
Epoch 10/20
224/224 [==============================] - 66s 293ms/step - loss: 0.3844 - accuracy: 0.8340 - val_loss: 1.4672 - val_accuracy: 0.5766
Epoch 11/20
224/224 [==============================] - 52s 232ms/step - loss: 0.3769 - accuracy: 0.8376 - val_loss: 1.5892 - val_accuracy: 0.5693
Epoch 12/20
224/224 [==============================] - 73s 327ms/step - loss: 0.3568 - accuracy: 0.8468 - val_loss: 1.6788 - val_accuracy: 0.5735
Epoch 13/20
224/224 [==============================] - 73s 326ms/step - loss: 0.3506 - accuracy: 0.8539 - val_loss: 1.6977 - val_accuracy: 0.5767
Epoch 14/20
224/224 [==============================] - 68s 304ms/step - loss: 0.3405 - accuracy: 0.8532 - val_loss: 1.7775 - val_accuracy: 0.5766
Epoch 15/20
224/224 [==============================] - 48s 213ms/step - loss: 0.3297 - accuracy: 0.8586 - val_loss: 1.8818 - val_accuracy: 0.5718
Epoch 16/20
224/224 [==============================] - 46s 206ms/step - loss: 0.3266 - accuracy: 0.8612 - val_loss: 1.9159 - val_accuracy: 0.5775
Epoch 17/20
224/224 [==============================] - 48s 213ms/step - loss: 0.3327 - accuracy: 0.8586 - val_loss: 1.8715 - val_accuracy: 0.5753
Epoch 18/20
224/224 [==============================] - 46s 207ms/step - loss: 0.3381 - accuracy: 0.8564 - val_loss: 1.7485 - val_accuracy: 0.5703
Epoch 19/20
224/224 [==============================] - 48s 212ms/step - loss: 0.3395 - accuracy: 0.8555 - val_loss: 1.8840 - val_accuracy: 0.5751
Epoch 20/20
224/224 [==============================] - 44s 198ms/step - loss: 0.3256 - accuracy: 0.8621 - val_loss: 1.8350 - val_accuracy: 0.5744
299/299 [==============================] - 5s 14ms/step

In [ ]:
import numpy as np

In [ ]:
from keras.callbacks import EarlyStopping
from sklearn.metrics import f1_score

seeds = [115]
f1=[]

X = df['req-text']
y = pd.factorize(df['age-bracket'])[0]

for seed in seeds:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed, stratify=y)
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(X_train)

    vocab_size = len(tokenizer.word_index) + 1

    sequences = tokenizer.texts_to_sequences(X_train)
    X_train = pad_sequences(sequences, maxlen=200)

    test_sequences = tokenizer.texts_to_sequences(X_test)
    X_test = pad_sequences(test_sequences, maxlen=200)

    X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=seed, stratify=y_train)

    y_train = np.array(y_train)
    y_test = np.array(y_test)

    model = create_model()

    early_stopping = EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)

    history = model.fit(
        X_train, y_train,
        epochs=20,
        batch_size=128,
        validation_data=(X_val, y_val),
        callbacks=[early_stopping]
    )

    y_pred = model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)

    f1.append(f1_score(y_test, y_pred_classes, average='weighted'))

print(f1)

Epoch 1/20
224/224 [==============================] - 22s 93ms/step - loss: 1.0148 - accuracy: 0.4616 - val_loss: 0.9378 - val_accuracy: 0.5387
Epoch 2/20
224/224 [==============================] - 20s 91ms/step - loss: 0.8383 - accuracy: 0.6092 - val_loss: 0.9192 - val_accuracy: 0.5569
Epoch 3/20
224/224 [==============================] - 20s 90ms/step - loss: 0.6899 - accuracy: 0.6934 - val_loss: 0.9558 - val_accuracy: 0.5632
Epoch 4/20
224/224 [==============================] - 21s 92ms/step - loss: 0.5887 - accuracy: 0.7421 - val_loss: 1.0577 - val_accuracy: 0.5630
Epoch 5/20
224/224 [==============================] - 20s 91ms/step - loss: 0.5236 - accuracy: 0.7761 - val_loss: 1.1238 - val_accuracy: 0.5619
Epoch 6/20
224/224 [==============================] - 21s 92ms/step - loss: 0.4721 - accuracy: 0.7961 - val_loss: 1.2226 - val_accuracy: 0.5519
Epoch 7/20
224/224 [==============================] - 21s 92ms/step - loss: 0.4437 - accuracy: 0.8071 - val_loss: 1.3476 - val_accuracy: 0.5586
Epoch 8/20
224/224 [==============================] - 20s 91ms/step - loss: 0.4159 - accuracy: 0.8175 - val_loss: 1.4575 - val_accuracy: 0.5512
299/299 [==============================] - 3s 8ms/step
[0.5692686089260219]

In [ ]:
f1

[0.5589216186232665,
 0.563559178078609,
 0.5721973033738913,
 0.5709944547936916,
 0.5681450579179833,
 0.5537780131059713,
 0.5659133099409086,
 0.5618926935315451]

## Cascata

In [ ]:
dict_class = pd.read_csv('../data/dict-class.csv', encoding='latin-1')

In [ ]:
dict_class

,Unnamed: 0,index,age-bracket,req-text,req-text-clean,Age,glex1,glex2,glex3,c,Age_,c50,c5025,cmean,c75
0,0,12957,a17-30,Necessito das tabelas de Índice de atualização...,necessito tabelas índice atualização contribui...,0,-1.631111,0.517476,0.246113,2,1,2,2,0,0
1,2,873,a17-30,"Prezados, estou elaborando um estudo sobre os ...",prezados elaborando estudo sobre impactos inve...,0,0.784827,4.547806,4.163538,1,1,1,1,1,0
2,11,45511,a31-42,"Prezados, Conforme redirecionamento do Suporte...",prezados conforme redirecionamento suporte sis...,1,-2.090903,-1.919023,-0.459755,3,2,3,3,3,3
3,17,7966,a43-xx,É possível obter uma lista de professores Titu...,possível obter lista professores titulares uni...,2,1.027527,0.866280,0.355635,1,3,1,1,1,0
4,28,44802,a17-30,Gostaria de solicitar duas infomações: 1. Exis...,gostaria solicitar duas infomações 1 existe ca...,0,1.606195,3.874015,1.784264,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2682,9532,24032,a17-30,"Prezados, Gostaria de obter uma cópia digitali...",prezados gostaria obter cópia digitalizada est...,0,1.262396,1.665968,1.044208,1,1,1,1,1,0
2683,9537,34095,a17-30,Gostaria de saber se há vagas para o cargo de ...,gostaria saber vagas cargo nutricionista técni...,0,1.604336,1.761439,0.021796,1,1,1,1,1,1
2684,9538,16968,a17-30,Estou classificado para o IFTO e gostaria de s...,classificado ifto gostaria aproveitado gostari...,0,1.533755,2.029393,1.558002,1,1,1,1,1,1
2685,9540,20928,a17-30,Gostaria de obter informações sobre as obras p...,gostaria obter informações sobre obras paralis...,0,1.798869,3.317710,1.770055,1,1,1,1,1,1
2686,9545,31601,a17-30,Visualizei no site www.acessoainformacao.ufrpe...,visualizei site wwwacessoainformacaoufrpebr ex...,0,1.726417,2.170952,0.585577,1,1,1,1,1,1

In [ ]:
df['req-text'][873]

'Prezados, estou elaborando um estudo sobre os impactos dos investimentos feitos pelo FGTS nas economias dos municípios brasileiros. Para tanto, necessito de dados detalhados por município acerca dos montantes aplicados em cada área de aplicação (saneamento, habitação e infraestrutura) em cada ano desde 2000. No site do FGTS, há um campo para consulta da contratação diária por município, entretanto, a pesquisa é lenta e fornece os resultados apenas para um município de cada vez. Considerando que temos mais de 5.000 municípios no país, a consulta dessas informações pelo site inviabiliza o estudo pretendido. Além disso, no site não constam informações sobre os valores desembolsados, que são os mais relevantes para a análise, apenas aparecem os dados dos valores contratados. Assim, venho por meio do e-SIC solicitar as seguintes informações, por município e por ano desde 2000 até 2014: valores contratados em cada área de aplicação do FGTS, valores desembolsados em cada área de aplicação, número de empregos gerados, população beneficiada e número de unidades no caso de habitação. Envio em anexo, com vistas a tornar meu pedido mais claro, um exemplo de relatório com os dados que necessito para o estudo. Ressalto a importância da obtenção desses dados para o estudo que se pretende realizar. Observar os impactos que os investimentos realizados pelo FGTS têm sobre a economia das localidades que recebem esses recursos é relevante para analisar a relevância do Fundo não só para os trabalhadores que possuem contas vinculadas, mas também para toda a população que, direta ou indiretamente, é beneficiada por essas aplicações.'

In [ ]:
result = df.reindex(dict_class['index'])

In [ ]:
result.shape, dict_class.shape

((2687, 137), (2687, 15))

In [ ]:
def get_age_class(age):
    if age == 'a17-30': return 0
    elif age == 'a31-42': return 1
    else: return 2

In [ ]:
import numpy as np
from sklearn import metrics
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping

In [ ]:
X = df['req-text']
df["Age"] = df['age-bracket'].apply(lambda x: get_age_class(x))
y = df['Age']

df_train = pd.read_csv('../data/train.csv')
df_test = pd.read_csv('../data/test.csv')

y_train = df_train['Age']
X_train = df_train['req-text']

y_test = df_test['Age']
X_test = df_test['req-text']

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

vocab_size = len(tokenizer.word_index) + 1

sequences = tokenizer.texts_to_sequences(X_train)
X_train = pad_sequences(sequences, maxlen=200)

test_sequences = tokenizer.texts_to_sequences(X_test)
X_test = pad_sequences(test_sequences, maxlen=200)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=115, stratify=y_train)

y_train = np.array(y_train)
y_test = np.array(y_test)

model = create_model()

early_stopping = EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)

history = model.fit(
        X_train, y_train,
        epochs=20,
        batch_size=128,
        validation_data=(X_val, y_val),
        callbacks=[early_stopping]
)

y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

df_test['Predict'] = y_pred_classes

print(metrics.f1_score(y_test, y_pred_classes, average='macro'))

Epoch 1/20
224/224 [==============================] - 21s 87ms/step - loss: 1.0180 - accuracy: 0.4623 - val_loss: 0.9362 - val_accuracy: 0.5377
Epoch 2/20
224/224 [==============================] - 20s 88ms/step - loss: 0.8365 - accuracy: 0.6089 - val_loss: 0.9141 - val_accuracy: 0.5513
Epoch 3/20
224/224 [==============================] - 20s 91ms/step - loss: 0.6883 - accuracy: 0.6909 - val_loss: 0.9689 - val_accuracy: 0.5578
Epoch 4/20
224/224 [==============================] - 20s 89ms/step - loss: 0.5868 - accuracy: 0.7404 - val_loss: 1.0235 - val_accuracy: 0.5618
Epoch 5/20
224/224 [==============================] - 20s 90ms/step - loss: 0.5156 - accuracy: 0.7735 - val_loss: 1.1862 - val_accuracy: 0.5656
Epoch 6/20
224/224 [==============================] - 20s 90ms/step - loss: 0.4697 - accuracy: 0.7958 - val_loss: 1.1921 - val_accuracy: 0.5668
Epoch 7/20
224/224 [==============================] - 20s 92ms/step - loss: 0.4402 - accuracy: 0.8073 - val_loss: 1.3047 - val_accuracy: 0.5626
Epoch 8/20
224/224 [==============================] - 21s 92ms/step - loss: 0.4149 - accuracy: 0.8153 - val_loss: 1.3899 - val_accuracy: 0.5625
Epoch 9/20
224/224 [==============================] - 20s 90ms/step - loss: 0.3940 - accuracy: 0.8239 - val_loss: 1.4530 - val_accuracy: 0.5594
Epoch 10/20
224/224 [==============================] - 20s 91ms/step - loss: 0.3882 - accuracy: 0.8263 - val_loss: 1.5925 - val_accuracy: 0.5604
Epoch 11/20
224/224 [==============================] - 21s 92ms/step - loss: 0.3673 - accuracy: 0.8336 - val_loss: 1.5767 - val_accuracy: 0.5667
299/299 [==============================] - 3s 8ms/step
0.5718622422275725

In [ ]:
dict_class = pd.read_csv('../data/dict-class.csv', encoding='latin-1')

In [ ]:
df_test = df_test.reset_index(drop=True)
dict_class = dict_class.reset_index(drop=True)

df_test['Unnamed: 0'] = df_test['Unnamed: 0'].astype(int)
dict_class['Unnamed: 0'] = dict_class['Unnamed: 0'].astype(int)

compare_test = df_test[df_test['Unnamed: 0'].isin(dict_class['Unnamed: 0'])]

In [ ]:
compare_test = compare_test
compare_dict = dict_class[['Unnamed: 0', 'c5025']]

compare = compare_test.merge(compare_dict, left_on='Unnamed: 0', right_on='Unnamed: 0')

In [ ]:
compare.head()

,Unnamed: 0,index,age-bracket,req-text,req-text-clean,Age,glex1,glex2,glex3,c,c50,c5025_x,cmean,c75,Predict,c5025_y
0,6,5476,a17-30,"Olá, Estou realizando meu trabalho de conclusã...",olá realizando trabalho conclusão curso estuda...,0,2.593333,3.206568,1.563178,0,0,0,0,0,0,0
1,10,3721,a43-xx,Gostaria de solicitar dados do consumo de ener...,gostaria solicitar dados consumo energia elétr...,2,3.444323,2.554219,0.308080,0,0,0,0,0,2,0
2,11,23181,a31-42,"Boa tarde, gostaria da quantidade de farmácias...",boa tarde gostaria quantidade farmácias popula...,1,1.050923,2.238745,1.804996,0,0,0,0,-1,0,0
3,13,971,a43-xx,"Prezado Sr. Geól. Paulo Ribeiro, segue comprov...",prezado sr geól paulo ribeiro segue comprovant...,2,-1.326335,-2.815001,-3.232350,2,2,2,2,2,1,2
4,16,5098,a17-30,"Prezados, Gostaria de solicitar o seguinte: a)...",prezados gostaria solicitar seguinte lista cla...,0,4.821409,5.661898,2.403441,0,0,0,0,0,0,0

In [ ]:
dict_class.shape, compare.shape, compare_test.shape, df_test.shape

((2752, 15), (545, 8), (545, 6), (9553, 6))

In [ ]:
metrics.f1_score(compare['Age'], compare[f'Predict'], average='macro'), metrics.f1_score(compare['Age'], compare['c5025_x'], average='macro')

(0.6335877862595419, 0.6281352235550709)

In [ ]:
compare.head(), compare.shape

(   Unnamed: 0 age-bracket                                           req-text  \
 0        3721      a43-xx  Gostaria de solicitar dados do consumo de ener...
 1        4461      a31-42  Bom dia, Eu tenho 35 anos e trabalhei por muit...
 2        4143      a31-42  Solicito, por gentileza, o Quadro de Referênci...
 3         750      a17-30    Solicito cópia do processo 48500.002286/2004-14
 4        2357      a17-30  Os dados solicitados são descritos em anexo, s...

                                       req-text-clean  Age  Predict  c5025  \
 0  gostaria solicitar dados consumo energia elétr...    2        2      1
 1  bom dia 35 anos trabalhei tempo informalidade ...    1        0      1
 2  solicito gentileza quadro referência servidore...    1        1      3
 3          solicito cópia processo 48500002286200414    0        2      1
 4  dados solicitados descritos anexo solicitase d...    0        0      2

    Age_
 0     2
 1     3
 2     3
 3     2
 4     2  ,
 (545, 8))

In [ ]:
merged_df = df_test.merge(compare[['Unnamed: 0', 'c5025_x']], on='Unnamed: 0', how='left')

In [ ]:
merged_df['Predict'] = merged_df['c5025_x'].combine_first(merged_df['Predict'])

In [ ]:
metrics.f1_score(merged_df['Age'], merged_df[f'Predict'], average='macro'), metrics.f1_score(df_test['Age'], df_test['Predict'], average='macro')

(0.570292054851879, 0.5718622422275725)